version: "3.8"

services:
  relational-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: relational-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Strong!Pass123"
    ports:
      - "1433:1433"
    volumes:
      - relational-data:/var/opt/mssql

  object-relational-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: objectrelational-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Strong!Pass123"
    ports:
      - "1434:1433"
    volumes:
      - objectrelational-data:/var/opt/mssql

  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: MyNoSqlDb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db

volumes:
  relational-data:
  objectrelational-data:
  mongo-data:
