// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wBialyBezdomnyEdition.Database.ObjectRelational;

#nullable disable

namespace wBialyDBAdapter.Migrations
{
    [DbContext(typeof(ORDB))]
    [Migration("20251130144921_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventTag_Event", b =>
                {
                    b.Property<int>("EventTagsTagID")
                        .HasColumnType("int");

                    b.Property<int>("EventsPostId")
                        .HasColumnType("int");

                    b.HasKey("EventTagsTagID", "EventsPostId");

                    b.HasIndex("EventsPostId");

                    b.ToTable("EventTag_Event");
                });

            modelBuilder.Entity("GastroTag_Gastro", b =>
                {
                    b.Property<int>("GastroTagsTagID")
                        .HasColumnType("int");

                    b.Property<int>("GastrosPostId")
                        .HasColumnType("int");

                    b.HasKey("GastroTagsTagID", "GastrosPostId");

                    b.HasIndex("GastrosPostId");

                    b.ToTable("GastroTag_Gastro");
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Event", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Gastro", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Gastros");
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Event", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("Tag_Event");
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Gastro", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<int>("GastroID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("Tag_Gastro");
                });

            modelBuilder.Entity("EventTag_Event", b =>
                {
                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Event", null)
                        .WithMany()
                        .HasForeignKey("EventTagsTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastroTag_Gastro", b =>
                {
                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Gastro", null)
                        .WithMany()
                        .HasForeignKey("GastroTagsTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Gastro", null)
                        .WithMany()
                        .HasForeignKey("GastrosPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
