// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wBialyDBAdapter.Database.ObjectRelational;

#nullable disable

namespace wBialyDBAdapter.Migrations
{
    [DbContext(typeof(ORDB))]
    [Migration("20251218201521_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventTag_Event", b =>
                {
                    b.Property<int>("EventTagsTagID")
                        .HasColumnType("int");

                    b.Property<int>("EventsPostId")
                        .HasColumnType("int");

                    b.HasKey("EventTagsTagID", "EventsPostId");

                    b.HasIndex("EventsPostId");

                    b.ToTable("EventTagsJoin", (string)null);

                    b.HasData(
                        new
                        {
                            EventTagsTagID = 1,
                            EventsPostId = 1
                        },
                        new
                        {
                            EventTagsTagID = 2,
                            EventsPostId = 2
                        },
                        new
                        {
                            EventTagsTagID = 7,
                            EventsPostId = 3
                        },
                        new
                        {
                            EventTagsTagID = 4,
                            EventsPostId = 4
                        },
                        new
                        {
                            EventTagsTagID = 8,
                            EventsPostId = 5
                        });
                });

            modelBuilder.Entity("GastroTag_Gastro", b =>
                {
                    b.Property<int>("GastroTagsTagID")
                        .HasColumnType("int");

                    b.Property<int>("GastrosPostId")
                        .HasColumnType("int");

                    b.HasKey("GastroTagsTagID", "GastrosPostId");

                    b.HasIndex("GastrosPostId");

                    b.ToTable("GastroTagsJoin", (string)null);

                    b.HasData(
                        new
                        {
                            GastroTagsTagID = 9,
                            GastrosPostId = 6
                        },
                        new
                        {
                            GastroTagsTagID = 10,
                            GastrosPostId = 7
                        },
                        new
                        {
                            GastroTagsTagID = 11,
                            GastrosPostId = 8
                        },
                        new
                        {
                            GastroTagsTagID = 16,
                            GastrosPostId = 9
                        },
                        new
                        {
                            GastroTagsTagID = 13,
                            GastrosPostId = 10
                        });
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Event", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            AddDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Admin",
                            Description = "Największy festiwal rockowy w mieście.",
                            Link = "https://event.com/rock",
                            Place = "Białystok Arena",
                            Title = "Rock Festival"
                        },
                        new
                        {
                            PostId = 2,
                            AddDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Admin",
                            Description = "Turniej siatkówki amatorskiej.",
                            Link = "https://event.com/sport",
                            Place = "Hala Sportowa",
                            Title = "Mecz siatkówki"
                        },
                        new
                        {
                            PostId = 3,
                            AddDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Curator",
                            Description = "Prezentacja dzieł lokalnych artystów.",
                            Link = "https://event.com/art",
                            Place = "Galeria Arsenał",
                            Title = "Wystawa sztuki współczesnej"
                        },
                        new
                        {
                            PostId = 4,
                            AddDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Admin",
                            Description = "Dzień pełen zabaw dla całej rodziny.",
                            Link = "https://event.com/family",
                            Place = "Park Planty",
                            Title = "Piknik rodzinny w parku"
                        },
                        new
                        {
                            PostId = 5,
                            AddDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "TechOrg",
                            Description = "Konferencja dla programistów i entuzjastów technologii.",
                            Link = "https://event.com/tech",
                            Place = "Centrum Konferencyjne",
                            Title = "Tech Conference 2025"
                        });
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Gastro", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Gastros");

                    b.HasData(
                        new
                        {
                            PostId = 6,
                            AddDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Admin",
                            Description = "Promocje na pizzę w całym mieście.",
                            Link = "https://gastro.com/pizza",
                            Place = "PizzaHouse",
                            Title = "Pizza Day"
                        },
                        new
                        {
                            PostId = 7,
                            AddDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Admin",
                            Description = "Święto kuchni wegańskiej.",
                            Link = "https://gastro.com/vegan",
                            Place = "GreenFood",
                            Title = "Vegan Fest"
                        },
                        new
                        {
                            PostId = 8,
                            AddDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Chef Wang",
                            Description = "Tydzień kuchni azjatyckiej z degustacjami.",
                            Link = "https://gastro.com/asian",
                            Place = "Asia Restaurant",
                            Title = "Asian Food Week"
                        },
                        new
                        {
                            PostId = 9,
                            AddDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Admin",
                            Description = "Świeże owoce morza prosto z wybrzeża.",
                            Link = "https://gastro.com/seafood",
                            Place = "Ocean Bistro",
                            Title = "Seafood Fiesta"
                        },
                        new
                        {
                            PostId = 10,
                            AddDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Pastry Chef",
                            Description = "Najlepsze desery w mieście w jednym miejscu.",
                            Link = "https://gastro.com/dessert",
                            Place = "Sweet Corner",
                            Title = "Dessert Paradise"
                        });
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Event", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("EventTags");

                    b.HasData(
                        new
                        {
                            TagID = 1,
                            EventID = 0,
                            Name = "Music"
                        },
                        new
                        {
                            TagID = 2,
                            EventID = 0,
                            Name = "Sport"
                        },
                        new
                        {
                            TagID = 3,
                            EventID = 0,
                            Name = "Culture"
                        },
                        new
                        {
                            TagID = 4,
                            EventID = 0,
                            Name = "Family"
                        },
                        new
                        {
                            TagID = 5,
                            EventID = 0,
                            Name = "Outdoor"
                        },
                        new
                        {
                            TagID = 6,
                            EventID = 0,
                            Name = "Education"
                        },
                        new
                        {
                            TagID = 7,
                            EventID = 0,
                            Name = "Art"
                        },
                        new
                        {
                            TagID = 8,
                            EventID = 0,
                            Name = "Technology"
                        });
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Gastro", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<int>("GastroID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("GastroTags");

                    b.HasData(
                        new
                        {
                            TagID = 9,
                            GastroID = 0,
                            Name = "Pizza"
                        },
                        new
                        {
                            TagID = 10,
                            GastroID = 0,
                            Name = "Vegan"
                        },
                        new
                        {
                            TagID = 11,
                            GastroID = 0,
                            Name = "Asian"
                        },
                        new
                        {
                            TagID = 12,
                            GastroID = 0,
                            Name = "Italian"
                        },
                        new
                        {
                            TagID = 13,
                            GastroID = 0,
                            Name = "Dessert"
                        },
                        new
                        {
                            TagID = 14,
                            GastroID = 0,
                            Name = "Healthy"
                        },
                        new
                        {
                            TagID = 15,
                            GastroID = 0,
                            Name = "FastFood"
                        },
                        new
                        {
                            TagID = 16,
                            GastroID = 0,
                            Name = "Seafood"
                        });
                });

            modelBuilder.Entity("EventTag_Event", b =>
                {
                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Event", null)
                        .WithMany()
                        .HasForeignKey("EventTagsTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastroTag_Gastro", b =>
                {
                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Gastro", null)
                        .WithMany()
                        .HasForeignKey("GastroTagsTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Gastro", null)
                        .WithMany()
                        .HasForeignKey("GastrosPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
