// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wBialyDBAdapter.Database.ObjectRelational;

#nullable disable

namespace wBialyDBAdapter.Migrations
{
    [DbContext(typeof(ORDB))]
    partial class ORDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventTag_Event", b =>
                {
                    b.Property<int>("EventTagsTagID")
                        .HasColumnType("int");

                    b.Property<int>("EventsPostId")
                        .HasColumnType("int");

                    b.HasKey("EventTagsTagID", "EventsPostId");

                    b.HasIndex("EventsPostId");

                    b.ToTable("EventTagsJoin", (string)null);

                    b.HasData(
                        new
                        {
                            EventTagsTagID = 1,
                            EventsPostId = 1
                        },
                        new
                        {
                            EventTagsTagID = 2,
                            EventsPostId = 2
                        });
                });

            modelBuilder.Entity("GastroTag_Gastro", b =>
                {
                    b.Property<int>("GastroTagsTagID")
                        .HasColumnType("int");

                    b.Property<int>("GastrosPostId")
                        .HasColumnType("int");

                    b.HasKey("GastroTagsTagID", "GastrosPostId");

                    b.HasIndex("GastrosPostId");

                    b.ToTable("GastroTagsJoin", (string)null);

                    b.HasData(
                        new
                        {
                            GastroTagsTagID = 3,
                            GastrosPostId = 3
                        },
                        new
                        {
                            GastroTagsTagID = 4,
                            GastrosPostId = 4
                        });
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Event", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            AddDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Admin",
                            Description = "Największy festiwal rockowy w mieście.",
                            Link = "https://event.com/rock",
                            Place = "Białystok Arena",
                            Title = "Rock Festival"
                        },
                        new
                        {
                            PostId = 2,
                            AddDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Admin",
                            Description = "Turniej siatkówki amatorskiej.",
                            Link = "https://event.com/sport",
                            Place = "Hala Sportowa",
                            Title = "Mecz siatkówki"
                        });
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Gastro", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Gastros");

                    b.HasData(
                        new
                        {
                            PostId = 3,
                            AddDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Admin",
                            Description = "Promocje na pizzę w całym mieście.",
                            Link = "https://gastro.com/pizza",
                            Place = "PizzaHouse",
                            Title = "Pizza Day"
                        },
                        new
                        {
                            PostId = 4,
                            AddDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Author = "Admin",
                            Description = "Święto kuchni wegańskiej.",
                            Link = "https://gastro.com/vegan",
                            Place = "GreenFood",
                            Title = "Vegan Fest"
                        });
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Event", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("EventTags");

                    b.HasData(
                        new
                        {
                            TagID = 1,
                            EventID = 0,
                            Name = "Music"
                        },
                        new
                        {
                            TagID = 2,
                            EventID = 0,
                            Name = "Sport"
                        });
                });

            modelBuilder.Entity("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Gastro", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<int>("GastroID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("GastroTags");

                    b.HasData(
                        new
                        {
                            TagID = 3,
                            GastroID = 0,
                            Name = "Pizza"
                        },
                        new
                        {
                            TagID = 4,
                            GastroID = 0,
                            Name = "Vegan"
                        });
                });

            modelBuilder.Entity("EventTag_Event", b =>
                {
                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Event", null)
                        .WithMany()
                        .HasForeignKey("EventTagsTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastroTag_Gastro", b =>
                {
                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Tag_Gastro", null)
                        .WithMany()
                        .HasForeignKey("GastroTagsTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wBialyDBAdapter.Database.ObjectRelational.Entities.Gastro", null)
                        .WithMany()
                        .HasForeignKey("GastrosPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
