/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const RegisterIndexLazyRouteImport = createFileRoute('/register/')()
const MessagesIndexLazyRouteImport = createFileRoute('/messages/')()
const LoginIndexLazyRouteImport = createFileRoute('/login/')()
const GastrosIndexLazyRouteImport = createFileRoute('/gastros/')()
const SecuritySettingsLazyRouteImport = createFileRoute('/security/settings')()
const SecurityLogsLazyRouteImport = createFileRoute('/security/logs')()
const GastrosGastroIdLazyRouteImport = createFileRoute('/gastros/$gastroId')()
const EventsEventIdLazyRouteImport = createFileRoute('/events/$eventId')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexLazyRoute = RegisterIndexLazyRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/register/index.lazy').then((d) => d.Route),
)
const MessagesIndexLazyRoute = MessagesIndexLazyRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/messages/index.lazy').then((d) => d.Route),
)
const LoginIndexLazyRoute = LoginIndexLazyRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))
const GastrosIndexLazyRoute = GastrosIndexLazyRouteImport.update({
  id: '/gastros/',
  path: '/gastros/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/gastros/index.lazy').then((d) => d.Route))
const SecuritySettingsLazyRoute = SecuritySettingsLazyRouteImport.update({
  id: '/security/settings',
  path: '/security/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/security/settings.lazy').then((d) => d.Route),
)
const SecurityLogsLazyRoute = SecurityLogsLazyRouteImport.update({
  id: '/security/logs',
  path: '/security/logs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/security/logs.lazy').then((d) => d.Route))
const GastrosGastroIdLazyRoute = GastrosGastroIdLazyRouteImport.update({
  id: '/gastros/$gastroId',
  path: '/gastros/$gastroId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/gastros/$gastroId.lazy').then((d) => d.Route),
)
const EventsEventIdLazyRoute = EventsEventIdLazyRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/events/$eventId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdLazyRoute
  '/gastros/$gastroId': typeof GastrosGastroIdLazyRoute
  '/security/logs': typeof SecurityLogsLazyRoute
  '/security/settings': typeof SecuritySettingsLazyRoute
  '/gastros': typeof GastrosIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/messages': typeof MessagesIndexLazyRoute
  '/register': typeof RegisterIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdLazyRoute
  '/gastros/$gastroId': typeof GastrosGastroIdLazyRoute
  '/security/logs': typeof SecurityLogsLazyRoute
  '/security/settings': typeof SecuritySettingsLazyRoute
  '/gastros': typeof GastrosIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/messages': typeof MessagesIndexLazyRoute
  '/register': typeof RegisterIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdLazyRoute
  '/gastros/$gastroId': typeof GastrosGastroIdLazyRoute
  '/security/logs': typeof SecurityLogsLazyRoute
  '/security/settings': typeof SecuritySettingsLazyRoute
  '/gastros/': typeof GastrosIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/messages/': typeof MessagesIndexLazyRoute
  '/register/': typeof RegisterIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$eventId'
    | '/gastros/$gastroId'
    | '/security/logs'
    | '/security/settings'
    | '/gastros'
    | '/login'
    | '/messages'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$eventId'
    | '/gastros/$gastroId'
    | '/security/logs'
    | '/security/settings'
    | '/gastros'
    | '/login'
    | '/messages'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId'
    | '/gastros/$gastroId'
    | '/security/logs'
    | '/security/settings'
    | '/gastros/'
    | '/login/'
    | '/messages/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdLazyRoute: typeof EventsEventIdLazyRoute
  GastrosGastroIdLazyRoute: typeof GastrosGastroIdLazyRoute
  SecurityLogsLazyRoute: typeof SecurityLogsLazyRoute
  SecuritySettingsLazyRoute: typeof SecuritySettingsLazyRoute
  GastrosIndexLazyRoute: typeof GastrosIndexLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  MessagesIndexLazyRoute: typeof MessagesIndexLazyRoute
  RegisterIndexLazyRoute: typeof RegisterIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastros/': {
      id: '/gastros/'
      path: '/gastros'
      fullPath: '/gastros'
      preLoaderRoute: typeof GastrosIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/settings': {
      id: '/security/settings'
      path: '/security/settings'
      fullPath: '/security/settings'
      preLoaderRoute: typeof SecuritySettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/logs': {
      id: '/security/logs'
      path: '/security/logs'
      fullPath: '/security/logs'
      preLoaderRoute: typeof SecurityLogsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastros/$gastroId': {
      id: '/gastros/$gastroId'
      path: '/gastros/$gastroId'
      fullPath: '/gastros/$gastroId'
      preLoaderRoute: typeof GastrosGastroIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdLazyRoute: EventsEventIdLazyRoute,
  GastrosGastroIdLazyRoute: GastrosGastroIdLazyRoute,
  SecurityLogsLazyRoute: SecurityLogsLazyRoute,
  SecuritySettingsLazyRoute: SecuritySettingsLazyRoute,
  GastrosIndexLazyRoute: GastrosIndexLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  MessagesIndexLazyRoute: MessagesIndexLazyRoute,
  RegisterIndexLazyRoute: RegisterIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
